# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Glasgow', max_length=128),
        ),
    ]
