# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profilePicture',
            field=models.ImageField(default='pet_images/wednesday.png', upload_to='pet_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(default='profile_images/user.jpeg', upload_to='profile_images'),
        ),
    ]
