# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0002_auto_20180318_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='showPets',
            field=models.BooleanField(default=False),
        ),
    ]
