# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0003_auto_20180318_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
