# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawpal', '0004_remove_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
