# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0006_auto_20180321_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('LIZARD', 'Lizard')], max_length=10),
        ),
    ]
