# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0007_auto_20180321_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.FloatField(default=154.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(default=154.0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='showPets',
            field=models.BooleanField(default=True),
        ),
    ]
