# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0008_auto_20180321_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='latitude',
            field=models.FloatField(default=55.8642),
        ),
        migrations.AlterField(
            model_name='pet',
            name='longitude',
            field=models.FloatField(default=4.2518),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(default=55.8642),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(default=4.2518),
        ),
    ]
