# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0009_auto_20180321_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='petPicture',
            new_name='profilePicture',
        ),
    ]
