# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpal', '0011_remove_userprofile_showpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
